sudo: required

language: bash
services: docker

env:
        # - VERSION=snapshot VARIANT=ubuntu
 - VERSION=snapshot VARIANT=alpine
 - VERSION=snapshot VARIANT=centos
   # - VERSION=snapshot VARIANT=scratch
   # - VERSION=snapshot VARIANT=vaapi
   # - VERSION=snapshot VARIANT=nvidia
   # - VERSION=4.1 VARIANT=ubuntu
   # - VERSION=4.1 VARIANT=alpine
   # - VERSION=4.1 VARIANT=centos
   # - VERSION=4.1 VARIANT=scratch
   # - VERSION=4.1 VARIANT=vaapi
   # - VERSION=4.1 VARIANT=nvidia

branches:
  only:
    - "master"

before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce

before_script:
  - env | sort
  - image="sstl:${VERSION}-${VARIANT}"

script:
  - docker build -t "${image}" --build-arg MAKEFLAGS="-j$(($(grep -c ^processor /proc/cpuinfo) + 1))" docker-images/${VERSION}/${VARIANT}
    #  - docker run --rm ${image} -buildconf

    #after_script:
    #  - docker images
# vim:set et ts=2 sw=2:
